### ISSUE TITLE
2.4.3 to 2.4.4 rc2 upgrade in CentOS6.8 not working 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/ceUpgrade#3]
Error during import: 

```
GLUU.[root@localhost backup_24]# ./import24.py /root/backup_24/
Traceback (most recent call last):
  File "./import24.py", line 535, in <module>
    main(sys.argv[1])
  File "./import24.py", line 482, in main
    current_version = getCurrentVersion()
  File "./import24.py", line 384, in getCurrentVersion
    return int(line.split(':')[-1].replace('.', '').strip())
ValueError: invalid literal for int() with base 10: '244rc2'
GLUU.[root@localhost backup_24]#
```

**Comment by tecoholic** [comment]
This should be in the community-edition repo.

**Comment by mzico** [comment]
Thanks @tecoholic
